name: Scrape Property Data

on:
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: node your-script-file.js  # Replace with the actual name of your script file

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: property-data
          path: artifacts/*.xlsx  # Adjust the path if needed
